# Generated by Django 2.2 on 2020-11-15 01:21

from django.db import migrations, models
import uploader.models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0003_auto_20201115_0321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=uploader.models.user_directory_path),
        ),
    ]
